module.exports = {
  MONGO_URI: process.env.MONGO_URI,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRY_IN: parseInt(process.env.JWT_EXPIRY_IN) || 90 * 86400,
  RAZORPAY_ID: process.env.RAZORPAY_ID,
  RAZORPAY_SECRET_KEY: process.env.RAZORPAY_SECRET_KEY,
  AWS_FILE_UPLOAD_LIMIT: process.env.AWS_FILE_UPLOAD_LIMIT,
  SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
  SMTP_ADMIN_EMAIL: process.env.SMTP_ADMIN_EMAIL,
  SMTP_USERNAME: process.env.SMTP_USERNAME,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,
  port: process.env.port,
  REGION: process.env.REGION,
  S3_BUCKET: process.env.S3_BUCKET,
  SALT_ROUNDS: process.env.SALT_ROUNDS,
  refreshTokenSecret: process.env.refreshTokenSecret,
  refreshTokenLife: parseInt(process.env.refreshTokenLife) || 91 * 86400,
  stage: process.env.stage,
  signedUrlExpireSeconds: 60 * 5,
};
